### ISSUE TITLE
Need durations for sessions

### ISSUE THREAD

**Issue by Faust1-2was-Aneo** [aneoconsulting/ArmoniK.Api#174]
The GUI needs to be able to see the duration of a session.

**Comment by aneojgurhem** [comment]
How do you define that (other than end - start) ?
We know when it starts as well as when it is cancelled.

**Comment by Faust1-2was-Aneo** [comment]
For a session that has ended, it would be the solution.
For a non-ended session, it would be the time that has passed since the beginning of the session.

For both ways, i could implement it in the GUI, but wouldn't it be interesting to have it in the API ?

**Comment by aneojgurhem** [comment]
You know the current time so you can still compute it. Adding this field would add more data in the response whereas you are able to compute it easily. Moreover, you may not want the duration but precisely the start of the session. It would add more load on the network for information you already have

**Comment by Faust1-2was-Aneo** [comment]
Ok, i shall implement it this way in the GUI then.
Thanks for the tips, i will close the issue.

**Comment by esoubiran-aneo** [comment]
@Faust1-2was-Aneo for the gui, here the code (could be improved) from the 0.7.0 version https://github.com/aneoconsulting/ArmoniK.Admin.GUI/pull/266/files#diff-c52427e5a8f892ef4680d342345f52ff00d09da234e01ca2e5937be7a8977024R167
