### ISSUE TITLE
Rename the gen folder with generated or generate

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK.Api#235]
In order to stay consistent with other folder name, we need to rename this folder (or even better, remove it and add the folder creation in your build process).

**Comment by aneojgurhem** [comment]
It is not created during build. It is needed by the proto3 vscode extension. I don't know how to inject the creation of this directory in the config. See .vscode/config (or whatever)

**Comment by esoubiran-aneo** [comment]
Why do you need to compile on save?

**Comment by aneojgurhem** [comment]
It helps to know if the created protos are valid

**Comment by aneojgurhem** [comment]
Already done!
