### ISSUE TITLE
Failed to connect to remote host: FD Shutdown

### ISSUE THREAD

**Issue by Pyrrha** [aneoconsulting/ArmoniK.Api#528]
Hello,

Since an upgrade of ArmoniK in 2.18.1, the Python SDK does no longer connect to ArmoniK controlplane.
I did upgrade from armonik==3.17.0 to armonik==3.18.1.

Is there a way something breaks between those versions?
We're using a proxy to connect through controlplane.

Thanks

**Comment by dbrasseur-aneo** [comment]
Hi, do you still have the issue ?
If so could you please send any logs would might have (control plane and client) ?
Thanks

**Comment by Pyrrha** [comment]
Hello,

Thanks for your feedback.

We're planning an ArmoniK upgrade today, I'll keep you in touch about it.
In parallel, I'll also upgrade my SDK version (even if it shouldn't be relevant for this issue)

**Comment by Pyrrha** [comment]
Hello,

The issue is not encountered anymore, I close this issue 😃
