### ISSUE TITLE
"Resource exhausted" while listing tasks

### ISSUE THREAD

**Issue by Pyrrha** [aneoconsulting/ArmoniK.Api#556]
Hello,

I encountered this error when calling a list_tasks() method using Pyhon SDK.

```
    result = client.list_tasks(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/armonik/client/tasks.py", line 330, in list_tasks
    response: ListTasksDetailedResponse = self._client.ListTasksDetailed(request)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "CLIENT: Received message larger than max (4624508 vs. 4194304)"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:x.x.x.x:8080 {grpc_message:"CLIENT: Received message larger than max (4624508 vs. 4194304)", grpc_status:8, created_time:"2024-09-06T08:16:08.774125466+00:00"}"
>
```

The status code looks a little bit weird compared to error message. I don't know much about GRPC, but could it be from a buffer that overflown?
If it's only a GRPC configuration to update, I suggest to also update it in package, for no reproduction of this issue in the future.

### Versions

* **ArmoniK:** 2.20.0
* **API:** 3.19.0
* **Core:** 0.24.4
* **Python SDK:** 3.17.1

Thanks.

**Comment by dbrasseur-aneo** [comment]
Hi, thanks for the report.
What page size did you request ?

**Comment by dbrasseur-aneo** [comment]
The default page size is 1000. Please don't use too big of page sizes because then the gRPC messages may be too big. If you encounter this again, please reduce the page size.

**Comment by Pyrrha** [comment]
Passing the buffer to 500 max was solving the issue.
It also solved another linked issue, throwing `FD shutdown` error. Different symptom, but it also was when pulling a lot of results from ControlPlane.
