### ISSUE TITLE
When build.yml must run ?

### ISSUE THREAD

**Issue by esoubiran-aneo** [aneoconsulting/ArmoniK.Api#56]
Is `build.yaml` must run only on PR, branch or every commit ? And what is the purpose of this file ? Check that files are correct or push to a package manager ?

Because of the use of an API Key for Nugget, Fork will failed every time and none of external PR will start checks

**Comment by dbrasseur-aneo** [comment]
My understanding is : 
- build.yaml is run on every commit
- build.yaml defines the actions tab in github
- In this repository, it will build the projects, and push the packages
- The API key is secret, and stored in the configuration of the repository, so yes, the pipeline in forks will fail when trying to push a package, unless you choose a different name and organization with your own API key

**Comment by esoubiran-aneo** [comment]
Yes but here the situation:
- I'm a random contributor
- Your a maintainer

How to know if my PR is fine? files are correctly lint? Actually, Actions doesn't run on external PR and build.yml seems to do every things, CI and CD!
